<script setup lang="ts">
withDefaults(defineProps<{
  image?: string
  colors?: Array[]
}>(), {
})
</script>

<template>
  <div class="h-full w-full flex flex-col items-center justify-center bg-black text-white relative">
    <img :src="image" class="absolute top-0 left-0 w-full h-full object-cover">
    <div class="w-full h-full absolute top-0 left-0">
      <svg height="100%" width="100%">
        <defs>
          <linearGradient id="0" x1="0" y1="0.5" x2="1" y2="0.5">
            <stop offset="0%" stop-color="#000000"/>
            <stop offset="33.33%" stop-color="rgba(0, 0, 0, 0.70)"/>
            <stop offset="100%" stop-color="rgba(0, 0, 0, 0)"/>
          </linearGradient>
        </defs>
        <rect fill="url(#0)" height="100%" width="100%"/>
      </svg>
      <svg height="100%" width="100%">
        <defs>
          <linearGradient id="0" x1="0" y1="0.5" x2="1" y2="0.5">
            <stop offset="0%" stop-color="#000000"/>
            <stop offset="33.33%" stop-color="rgba(0, 0, 0, 0.70)"/>
            <stop offset="100%" stop-color="rgba(0, 0, 0, 0)"/>
          </linearGradient>
        </defs>
        <rect fill="url(#0)" height="100%" width="100%"/>
      </svg>
      <svg height="100%" width="100%">
        <defs>
          <linearGradient id="0" x1="0" y1="0.5" x2="1" y2="0.5">
            <stop offset="0%" stop-color="rgba(0, 0, 0, 0)"/>
            <stop offset="33.33%" stop-color="rgba(0, 0, 0, 0.33)"/>
            <stop offset="100%" stop-color="#000000"/>
          </linearGradient>
        </defs>
        <rect fill="url(#0)" height="100%" width="100%"/>
      </svg>
    </div>
    <div class="flex flex-col items-start justify-start w-full px-10 mb-24">
      <p class="text-4xl">Palette Generated by</p>
      <h1 class="text-8xl">Palette Pilot</h1>
    </div>
    <div class="w-full flex items-start justify-end px-10 gap-x-3 pt-6">
      <div v-for="(color, index) in colors" :key="index" class="bg-gray-400/40 p-2 rounded-lg backdrop-blur-xl">
        <div class="size-18 rounded-md" :style="{ backgroundColor: color.hex }"></div>
      </div>
    </div>
  </div>
</template>
